#! /usr/bin/python
import os
import subprocess
import sys

def main():
    old_cwd=os.getcwd()
    os.chdir(os.path.expanduser('~/gamr7'))
    cmd = "ctags -R --tag-relative=yes --languages=Python --python-kinds=-i -f ~/gamr7/tags ~/gamr7"
    subprocess.Popen(cmd, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, close_fds=True).stdin
    os.chdir(old_cwd)

sys.exit(main())
